import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Container } from "@/components/ui/container";
import { FileText, ChevronRight } from "lucide-react";

const LAST_UPDATED = "March 1, 2026";

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using the InteliFleet platform, including our website, mobile applications, and all associated services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree to these Terms, please do not use the Service.

These Terms constitute a legally binding agreement between you (or the entity you represent) and InteliFleet ("Company," "we," "our," or "us"). We reserve the right to update these Terms at any time, and your continued use of the Service after any changes constitutes acceptance of the revised Terms.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `InteliFleet provides a fleet intelligence platform that includes real-time GPS tracking, fuel monitoring, driver analytics, geofencing, maintenance scheduling, compliance document management, and reporting tools (collectively, "Features").

The Service is delivered via a web-based dashboard, mobile application, and associated REST APIs. Certain features require the installation of compatible hardware telemetry devices, which may be subject to separate hardware terms. InteliFleet reserves the right to modify, suspend, or discontinue any Feature at any time with reasonable prior notice.`,
  },
  {
    id: "accounts",
    title: "3. Account Registration & Responsibilities",
    content: `To use the Service, you must register for an account by providing accurate, complete, and current information. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.

You must:
• Be at least 18 years of age or the age of legal majority in your jurisdiction.
• Provide accurate business or personal information during registration.
• Promptly notify us of any unauthorized access or security breach.
• Not share your credentials with third parties outside your organization.
• Not create accounts for the purpose of misuse, competitive analysis, or resale without prior written consent.

We reserve the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    id: "subscriptions",
    title: "4. Subscriptions & Payment",
    content: `InteliFleet offers subscription-based access to the Service. Pricing plans, billing cycles, and included features are as described on our Pricing page and may be updated with 30 days' notice.

Payments are processed via authorized payment gateways. By providing payment information, you authorize us to charge applicable fees on a recurring basis in accordance with your selected plan.

Fees are non-refundable except where required by applicable law or as explicitly stated in your subscription agreement. Failure to pay fees may result in suspension or termination of your account. All applicable taxes are the responsibility of the subscriber.`,
  },
  {
    id: "usage",
    title: "5. Acceptable Use Policy",
    content: `You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not:

• Use the Service to track individuals without their lawful consent where required by applicable law.
• Attempt to reverse-engineer, decompile, or extract source code from the platform.
• Use automated tools (bots, scrapers) to access the Service without authorization.
• Transmit harmful, malicious, or fraudulent data through the Service.
• Impersonate any person or entity, or misrepresent your affiliation with any organization.
• Use the Service in any manner that could disable, overburden, or impair its operation.
• Resell or sublicense access to the Service without explicit written permission.

InteliFleet reserves the right to terminate access for any user found in violation of this policy.`,
  },
  {
    id: "data",
    title: "6. Data Ownership & Usage",
    content: `You retain full ownership of all data submitted to or generated by your use of the Service ("Customer Data"), including vehicle telemetry, driver information, and organizational data.

By using the Service, you grant InteliFleet a limited, non-exclusive license to process, store, and display Customer Data solely for the purpose of providing the Service to you.

InteliFleet may use aggregated, anonymized, and de-identified data for product improvement, research, and analytics purposes. This aggregated data will not identify you or your organization. We will not sell your Customer Data to third parties.`,
  },
  {
    id: "ip",
    title: "7. Intellectual Property",
    content: `All intellectual property rights in the Service — including but not limited to software, algorithms, UI/UX designs, trademarks, logos, and documentation — are owned by InteliFleet or its licensors.

These Terms do not grant you any rights to InteliFleet's intellectual property except the limited right to use the Service as described herein. Any feedback, suggestions, or ideas you provide regarding the Service may be used by InteliFleet without obligation or compensation to you.`,
  },
  {
    id: "privacy",
    title: "8. Privacy",
    content: `Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the collection, use, and disclosure of information as described in our Privacy Policy.

You are responsible for ensuring that any personal data of third parties (including drivers and employees) that you submit to the Service is collected and processed in compliance with applicable data protection laws.`,
  },
  {
    id: "warranty",
    title: "9. Disclaimer of Warranties",
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

InteliFleet does not warrant that:
• The Service will be uninterrupted, timely, secure, or error-free.
• Any GPS data, telemetry readings, or alerts will be 100% accurate at all times.
• Any defects will be corrected.

Use of the Service is at your sole risk. GPS and IoT data is subject to inherent limitations of hardware and network connectivity.`,
  },
  {
    id: "liability",
    title: "10. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL INTELIFLEET BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES — INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL — ARISING FROM YOUR USE OR INABILITY TO USE THE SERVICE.

InteliFleet's total liability to you for any claims arising under these Terms shall not exceed the total fees paid by you in the 12 months preceding the claim.

This limitation applies regardless of the form of action, whether in contract, tort, or otherwise, even if InteliFleet has been advised of the possibility of such damages.`,
  },
  {
    id: "termination",
    title: "11. Termination",
    content: `Either party may terminate the subscription at any time in accordance with the billing cycle. Upon termination:

• Your access to the Service will be disabled.
• We will retain your Customer Data for 30 days post-termination, after which it may be permanently deleted.
• You may request an export of your data within the 30-day retention window.

InteliFleet may immediately suspend or terminate your account if you materially breach these Terms, including but not limited to non-payment, misuse, or unauthorized access.`,
  },
  {
    id: "governing",
    title: "12. Governing Law & Disputes",
    content: `These Terms are governed by the laws of India, without regard to its conflict of law provisions. Any disputes arising from or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the courts located in Bhubaneswar, Odisha, India.

Before initiating any legal proceedings, parties agree to attempt good-faith negotiation for at least 30 days. If unresolved, disputes may be referred to binding arbitration in accordance with the Arbitration and Conciliation Act, 1996.`,
  },
  {
    id: "contact",
    title: "13. Contact Information",
    content: `If you have questions about these Terms, please contact us:

Email: legal@intelifleet.com
Phone: +91 9777303064
Address: InteliFleet Technologies, Bhubaneswar, Odisha, India — 751001

We aim to respond to all legal inquiries within 5 business days.`,
  },
];

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState("acceptance");

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActiveSection(entry.target.id);
        });
      },
      { rootMargin: "-30% 0px -60% 0px" },
    );
    sections.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <div className="min-h-screen pt-20">
      {/* Hero */}
      <section className="pt-10 pb-12 border-b">
        <Container>
          <div className="max-w-3xl">
            <motion.h1
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.05 }}
              className="text-3xl md:text-5xl font-bold tracking-tight mb-4"
            >
              Terms and Conditions
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="text-muted-foreground md:text-lg leading-relaxed"
            >
              Please read these terms carefully before using InteliFleet. By
              accessing our platform, you agree to be bound by these terms.
            </motion.p>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.15 }}
              className="flex flex-wrap items-center gap-6 mt-6 text-sm text-muted-foreground"
            >
              <span className="px-3 py-1 rounded-full bg-muted text-xs font-medium">
                Last updated: {LAST_UPDATED}
              </span>
              <span>{sections.length} sections</span>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* Body */}
      <section className="py-12 pb-24">
        <Container className="flex gap-12">
          {/* Sticky sidebar TOC */}
          <aside className="hidden lg:block w-64 shrink-0">
            <div className="sticky top-24">
              <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-4">
                Contents
              </p>
              <nav className="space-y-1">
                {sections.map((s) => (
                  <a
                    key={s.id}
                    href={`#${s.id}`}
                    onClick={() => setActiveSection(s.id)}
                    className={`block text-sm py-1.5 px-3 rounded-lg transition-all duration-200 leading-snug ${
                      activeSection === s.id
                        ? "bg-primary/10 text-primary font-medium"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    }`}
                  >
                    {s.title}
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Main content */}
          <main className="flex-1 min-w-0">
            <div className="space-y-12">
              {sections.map((s, i) => (
                <motion.section
                  key={s.id}
                  id={s.id}
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.03 }}
                  className="scroll-mt-28"
                >
                  <h2 className="text-xl font-bold mb-4 pb-3 border-b">
                    {s.title}
                  </h2>
                  <div className="text-muted-foreground leading-relaxed text-[15px] space-y-3 whitespace-pre-line">
                    {s.content}
                  </div>
                </motion.section>
              ))}
            </div>

            <div className="mt-16 pt-8 border-t text-sm text-muted-foreground">
              <p>
                These Terms and Conditions were last updated on{" "}
                <span className="font-medium text-foreground">
                  {LAST_UPDATED}
                </span>
                . For questions, contact us at{" "}
                <a
                  href="mailto:legal@intelifleet.com"
                  className="text-primary hover:underline"
                >
                  legal@intelifleet.com
                </a>
                .
              </p>
            </div>
          </main>
        </Container>
      </section>
    </div>
  );
}
